import json

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Perbandingan Model Klasifikasi Decision Tree dan Random Forest (Dataset Play Tennis)\n",
            "\n",
            "## 1. Deskripsi Proyek\n",
            "Proyek ini bertujuan untuk melakukan analisis data klasifikasi menggunakan node-node yang tersedia di KNIME serta membandingkannya menggunakan bahasa pemrograman Python. Dataset yang digunakan adalah **Play Tennis**, yang berisi kondisi cuaca (seperti Outlook, Temperature, Humidity, Wind) untuk menentukan target apakah seseorang akan bermain tenis atau tidak (`PlayTennis` sebagai label).\n",
            "\n",
            "Pada analisis ini dilakukan perbandingan dua algoritma klasifikasi:\n",
            "1. **Decision Tree**\n",
            "2. **Random Forest**\n",
            "\n",
            "Perbandingan dilakukan berdasarkan hasil evaluasi model menggunakan Scorer atau Confusion Matrix, terutama pada metrik Akurasi.\n",
            "\n",
            "## 2. Mengenal Random Forest & Decision Tree\n",
            "- **Decision Tree**: Memecah data ke dalam aturan memecah berdasarkan kondisi secara rekursif (seperti pohon percabangan) untuk membuat keputusan tunggal.\n",
            "- **Random Forest**: Algoritma ansambel (kumpulan) yang terdiri dari banyak Decision Tree. Setiap tree dikembangkan dari sampel acak data. \n",
            "\n",
            "### Rumus Prediksi Random Forest (Majority Voting)\n",
            "Setiap tree akan menghasilkan prediksi masing-masing, kemudian hasil akhirnya ditentukan berdasarkan suara terbanyak atau *majority voting*.\n",
            "\n",
            "Untuk klasifikasi, hasil prediksi Random Forest dapat ditulis sebagai:\n",
            "$$ \\hat{y} = \\text{mode} \\{ h_1(x), h_2(x), \\dots, h_K(x) \\} $$\n",
            "\n",
            "Keterangan Rumus:\n",
            "- $\\hat{y}$ = hasil prediksi akhir\n",
            "- $h_i(x)$ = hasil prediksi dari Decision Tree ke-i\n",
            "- $K$ = jumlah pohon dalam Random Forest\n",
            "- $\\text{mode}$ = kelas yang paling banyak muncul\n",
            "\n",
            "**Contoh Majority Voting:**\n",
            "Jika ada 5 pohon dengan hasil prediksi: `Yes, Yes, No, Yes, No`\n",
            "Maka hasil akhirnya adalah `Yes` karena kelas \"Yes\" paling banyak dipilih oleh pohon-pohon di dalam Random Forest.\n",
            "\n",
            "## 3. Penjelasan Workflow KNIME\n",
            "Berdasarkan workflow KNIME yang Anda gunakan, alur analisis dirancang secara terpisah *(branching)* setelah memuat dataset. Hal ini bertujuan agar Decision Tree dan Random Forest menerima dan diproses dari sumber uji yang 100% sama agar perbandingannya adil.\n",
            "\n",
            "### Node yang Digunakan:\n",
            "1. **Excel Reader**: Berfungsi untuk menjembatani dan membaca dataset murni dari file `play_tennis_knime.xlsx`.\n",
            "2. **Table Partitioner**: Digunakan untuk membagi dataset menjadi dua kelompok (*Training Data* dan *Testing Data*). Berdasarkan gambar yang Anda tunjukkan, pengaturan **Relative Size = 80**. Artinya 80% dari total 14 baris (11 baris) masuk ke *Training* dan sisa 20% (3 baris) masuk sebagai *Testing*.\n",
            "3. **Decision Tree Learner**: Membangun model Decision Tree murni berdasarkan data pelatihan.\n",
            "4. **Decision Tree Predictor**: Melakukan *score* prediksi kelas untuk 3 baris data uji berdasarkan model Decision Tree dari node lerner.\n",
            "5. **Random Forest Learner**: Membuat variasi pohon-pohon keputusan (ensemble) secara banyak sekaligus atas data latih.\n",
            "6. **Random Forest Predictor**: Menghasilkan klasifikasi gabungan untuk memprediksi hasil data uji.\n",
            "7. **Scorer**: Menghitung ketepatan (*accuracy, error rate*, dll.) dari tebakan algoritma dibandingkan kebenaran (*ground truth*).\n",
            "\n",
            "> *Silakan isi screenshot workflow KNIME Anda di sini*\n",
            "\n",
            "## 4. Evaluasi Hasil Scorer (Berdasarkan Gambar)\n",
            "Mengacu pada tangkapan layar matriks hasil **Random Forest Predictor > Scorer** Anda:\n",
            "- Terdapat `Yes` memprediksi `Yes` *(True Positive)* = 2 data\n",
            "- Terdapat `Yes` (Aktual) namun terprediksi `No` *(False Negative)* = 1 data\n",
            "- Total **Data Uji = 3 baris**\n",
            "\n",
            "**Analisis Perhitungan Evaluasinya:**\n",
            "- **Accuracy**: Jumlah diprediksi benar dibandingkan seluruh uji -> $2 / 3 = 0.666$ atau **66.67%**.\n",
            "- **Error Rate**: Persentase meleset -> $1 / 3 = 0.333$ atau **33.33%**.\n",
            "\n",
            "Kasus ini wajar mengingat total record uji hanya sangat sedikit (3 record), meleset 1 tebakan *entropy/information gain* sudah membuat error 33%.\n",
            "\n",
            "---\n",
            "\n",
            "## 5. Implementasi Ulang dengan Python\n",
            "Sebagai pelengkap dan perbandingan, kami mensimulasikan kembali tahapan KNIME Anda menggunakan pustaka **Scikit-Learn** di Python."
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "import pandas as pd\n",
            "from sklearn.model_selection import train_test_split\n",
            "from sklearn.tree import DecisionTreeClassifier\n",
            "from sklearn.ensemble import RandomForestClassifier\n",
            "from sklearn.metrics import accuracy_score, confusion_matrix\n",
            "from sklearn.preprocessing import LabelEncoder\n",
            "\n",
            "# 1. Menyusun Dataset Play Tennis Murni\n",
            "data = {\n",
            "    'Outlook': ['Sunny','Sunny','Overcast','Rain','Rain','Rain','Overcast','Sunny','Sunny','Rain','Sunny','Overcast','Overcast','Rain'],\n",
            "    'Temperature': ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild'],\n",
            "    'Humidity': ['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal','Normal','High','Normal','High'],\n",
            "    'Wind': ['Weak','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Strong'],\n",
            "    'PlayTennis': ['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']\n",
            "}\n",
            "df = pd.DataFrame(data)\n",
            "\n",
            "# 2. Pre-processing: Label Encoding (diperlukan untuk Scikit-Learn)\n",
            "le = LabelEncoder()\n",
            "for col in df.columns:\n",
            "    df[col] = le.fit_transform(df[col])\n",
            "\n",
            "X = df.drop('PlayTennis', axis=1)\n",
            "y = df['PlayTennis']\n",
            "\n",
            "# 3. Membagi Partisi 80% (Table Partitioner KNIME)\n",
            "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
            "\n",
            "print(f\"Data Latih: {len(X_train)} baris, Data Uji: {len(X_test)} baris (Total: {len(X)})\\n\")\n",
            "\n",
            "# 4. Analisis Decision Tree\n",
            "dt_model = DecisionTreeClassifier(random_state=42)\n",
            "dt_model.fit(X_train, y_train)\n",
            "dt_pred = dt_model.predict(X_test)\n",
            "\n",
            "print(\">>> Hasil Evaluasi Decision Tree <<<\")\n",
            "print(f\"Akurasi        : {accuracy_score(y_test, dt_pred) * 100:.2f}%\")\n",
            "print(\"Confusion Matrix:\\n\", confusion_matrix(y_test, dt_pred))\n",
            "print(\"-\" * 35)\n",
            "\n",
            "# 5. Analisis Random Forest\n",
            "rf_model = RandomForestClassifier(n_estimators=100, random_state=42)\n",
            "rf_model.fit(X_train, y_train)\n",
            "rf_pred = rf_model.predict(X_test)\n",
            "\n",
            "print(\"\\n>>> Hasil Evaluasi Random Forest <<<\")\n",
            "print(f\"Akurasi        : {accuracy_score(y_test, rf_pred) * 100:.2f}%\")\n",
            "print(\"Confusion Matrix:\\n\", confusion_matrix(y_test, rf_pred))"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 6. Kesimpulan\n",
            "Pada dataset yang cukup kecil (`Play Tennis` dengan 14 total baris), perbedaan skor antara satu model Decision Tree dan Random Forest cenderung bervariasi bergantung pada fitur mana saja yang masuk ke dalam *Testing Data* (akibat acak sampling pada *Table Partitioner*). \n",
            "\n",
            "- **Decision Tree** sering kali bisa menemukan pemisahan kelas tunggal yang akurat secara sederhana pada dataset ini, sehingga terkadang akurasinya nampak sangat tinggi (bahkan sampai 100% pada *testing data* tertentu). \n",
            "- **Random Forest**, yang melakukan *voting* dari banyak pohon dengan data sampel, mungkin mendapati mayoritas pohon memprediksi kategori berlawanan akibat satu karakteristik cuaca, menghasilkan satu miss pada data tes yang membelokkan akurasi (misal 66.6% seperti hasil yang divisualisasikan oleh Scorer KNIME). \n",
            "\n",
            "Meski begitu, **secara teori** Random Forest lebih diunggulkan dan stabil secara kolektif *(ensemble)* karena sanggup menghindari *overfitting* yang mana hampir selalu menjebak Decision Tree tunggal pada dataset kompleks industri."
        ]
    }
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open("materi/analisa-data-menggunakan-random-forest.ipynb", "w") as f:
    json.dump(notebook, f, indent=2)
